### ISSUE TITLE
Preventing GitHub workflows from running when the issue is still open

### ISSUE THREAD

**Issue by eneko** [eneko/Blog#18]
I've been working on some updates for my Blog Engine here and there. One of the updates was to prevent the [publishing workflow](https://github.com/eneko/Blog/blob/main/.github/workflows/issue.yml) from being triggered while working on an article. 

Before I was using a label Draft, and manually checking for it in my Swift code. But at that point, the only way to stop the workflow would be to make it fail.

Instead, using [action `if` conditions](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions), I can check for the issue to be closed (what I treat as "published"), in which case the workflow can continue:

```yaml
jobs:
  generateSocialPreview:
    runs-on: macos-latest
    if: github.event.issue.user.login == github.repository_owner && github.event.issue.state == 'closed'
    steps:
       - ...
```

Note I'm also checking the issue author is me, the owner of the [Blog](https://github.com/eneko/Blog) repo.

As a result, the workflow run will still appear in the Actions tab, but greyed out indicating the skipped jobs:

![Screen Shot 2021-01-06 at 8 43 57 AM](https://user-images.githubusercontent.com/32922/103795954-7c8e0580-4ffb-11eb-8834-0909d615dd87.png)

![Screen Shot 2021-01-06 at 8 43 48 AM](https://user-images.githubusercontent.com/32922/103795947-7ac44200-4ffb-11eb-8458-860973989556.png)
